"use server";
import { z } from "zod";

const UserSchema = z.object({
  "name": z.string().optional(),
  "user_details_tab": z.any().optional(),
  "enabled": z.number().optional(),
  "section_break_3": z.any().optional(),
  "email": z.string().optional(),
  "first_name": z.string().optional(),
  "middle_name": z.string().optional(),
  "last_name": z.string().optional(),
  "column_break0": z.any().optional(),
  "full_name": z.string().optional(),
  "username": z.string().optional(),
  "column_break_11": z.any().optional(),
  "language": z.string().optional(),
  "time_zone": z.any().optional(),
  "send_welcome_email": z.number().optional(),
  "unsubscribed": z.number().optional(),
  "user_image": z.any().optional(),
  "roles_permissions_tab": z.any().optional(),
  "sb1": z.any().optional(),
  "role_profile_name": z.string().optional(),
  "roles_html": z.any().optional(),
  "roles": z.array(z.object({"role": z.string()})).optional(),
  "sb_allow_modules": z.any().optional(),
  "module_profile": z.string().optional(),
  "modules_html": z.any().optional(),
  "block_modules": z.array(z.object({"module": z.string()})).optional(),
  "home_settings": z.any().optional(),
  "short_bio": z.any().optional(),
  "gender": z.string().optional(),
  "birth_date": z.string().optional(),
  "interest": z.any().optional(),
  "column_break_26": z.any().optional(),
  "phone": z.string().optional(),
  "location": z.string().optional(),
  "bio": z.any().optional(),
  "column_break_22": z.any().optional(),
  "mobile_no": z.string().optional(),
  "settings_tab": z.any().optional(),
  "desk_settings_section": z.any().optional(),
  "mute_sounds": z.number().optional(),
  "desk_theme": z.any().optional(),
  "banner_image": z.any().optional(),
  "navigation_settings_section": z.any().optional(),
  "search_bar": z.number().optional(),
  "notifications": z.number().optional(),
  "list_settings_section": z.any().optional(),
  "list_sidebar": z.number().optional(),
  "bulk_actions": z.number().optional(),
  "view_switcher": z.number().optional(),
  "form_settings_section": z.any().optional(),
  "form_sidebar": z.number().optional(),
  "timeline": z.number().optional(),
  "dashboard": z.number().optional(),
  "change_password": z.any().optional(),
  "new_password": z.any().optional(),
  "logout_all_sessions": z.number().optional(),
  "reset_password_key": z.string().optional(),
  "last_reset_password_key_generated_on": z.string().optional(),
  "last_password_reset_date": z.string().optional(),
  "redirect_url": z.any().optional(),
  "document_follow_notifications_section": z.any().optional(),
  "document_follow_notify": z.number().optional(),
  "document_follow_frequency": z.any().optional(),
  "column_break_75": z.any().optional(),
  "follow_created_documents": z.number().optional(),
  "follow_commented_documents": z.number().optional(),
  "follow_liked_documents": z.number().optional(),
  "follow_assigned_documents": z.number().optional(),
  "follow_shared_documents": z.number().optional(),
  "email_settings": z.any().optional(),
  "email_signature": z.any().optional(),
  "thread_notify": z.number().optional(),
  "send_me_a_copy": z.number().optional(),
  "allowed_in_mentions": z.number().optional(),
  "user_emails": z.array(z.object({"email_account": z.string(), "email_id": z.string(), "column_break_3": z.any(), "awaiting_password": z.number(), "used_oauth": z.number(), "enable_outgoing": z.number()})).optional(),
  "workspace_section": z.any().optional(),
  "default_workspace": z.string().optional(),
  "app_section": z.any().optional(),
  "default_app": z.any().optional(),
  "sb2": z.any().optional(),
  "defaults": z.array(z.object({"defkey": z.string(), "defvalue": z.string()})).optional(),
  "sb3": z.any().optional(),
  "simultaneous_sessions": z.number().optional(),
  "restrict_ip": z.any().optional(),
  "last_ip": z.string().optional(),
  "column_break1": z.any().optional(),
  "login_after": z.number().optional(),
  "user_type": z.string().optional(),
  "last_active": z.string().optional(),
  "section_break_63": z.any().optional(),
  "login_before": z.number().optional(),
  "bypass_restrict_ip_check_if_2fa_enabled": z.number().optional(),
  "last_login": z.string().optional(),
  "last_known_versions": z.string().optional(),
  "third_party_authentication": z.any().optional(),
  "social_logins": z.array(z.object({"provider": z.string(), "section_break_0": z.any(), "username": z.string(), "column_break_0": z.any(), "userid": z.string()})).optional(),
  "api_access": z.any().optional(),
  "api_key": z.string().optional(),
  "generate_keys": z.any().optional(),
  "column_break_65": z.any().optional(),
  "api_secret": z.any().optional(),
  "onboarding_status": z.any().optional(),
  "connections_tab": z.any().optional()
});

export type User = z.infer<typeof UserSchema>;

export async function createUser(doc: User, apiKey: string, apiSecret: string): Promise<User> {
  const response = await fetch(`/api/v1/resource/User`, {
    method: "POST",
    headers: {
      "Authorization": `token ${apiKey}:${apiSecret}`,
      "X-Action-Source": "AI",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(doc),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Failed to create user: ${errorBody}`);
  }
  
  
  
  const result = await response.json();
  return result.data;
}